### ISSUE TITLE
Error running selectDVforEV function

### ISSUE THREAD

**Issue by DanielZuleta** [julienvollering/MIAmaxent#9]
Dear @julienvollering,

We got this error message and have not been able to figure out what's going on.

code:
`DVselect <- selectDVforEV(dvdata, alpha = 0.001, quiet = TRUE)`

Error message:
```
Error in if (nrow(ctable) == 1 || ctable$P[1] > alpha) { : 
  missing value where TRUE/FALSE needed
```

We are willing to share the `dvdata` object if you provide your email.
Thanks,

**Comment by julienvollering** [comment]
Hi Daniel,

Thanks for reporting this!

Please do send me the dvdata object: <julienvollering at gmail.com>. It will make it easier for me to search for the cause of the error.

________________________________
From: DanielZuleta ***@***.***>
Sent: Friday, March 26, 2021, 21:21
To: julienvollering/MIAmaxent
Cc: Julien Martin Marie Vollering; Mention
Subject: [julienvollering/MIAmaxent] Error running selectDVforEV function (#9)


Dear @julienvollering<https://github.com/julienvollering>,

We got this error message and have not been able to figure out what's going on.

code:
DVselect <- selectDVforEV(dvdata, alpha = 0.001, quiet = TRUE)

Error message:

Error in if (nrow(ctable) == 1 || ctable$P[1] > alpha) { :
  missing value where TRUE/FALSE needed


We are willing to share the dvdata object if you provide your email.
Thanks,

**Comment by julienvollering** [comment]
Hi @DanielZuleta,

Seems the error was caused by equivalent derived variables for a single explanatory variable. Namely, a linear transformation and a deviation transformation resulted in equivalent values (exactly inversely related). That is a quirk of the data that I haven't seen before.

I've introduced a fix into the source code to avoid the error. You can install the development version from GitHub and try again. Please reopen the issue if it persists for you.

**Comment by DanielZuleta** [comment]
Wow! that's very interesting. 
It works now, but I am curious about how did you fix the issue in the function. Specifically, does it now remove one of the equivalent variables?

**Comment by julienvollering** [comment]
It does not remove one of the equivalent variables, but since they are equivalent, only one of them will be selected (at most). Specifically, the second of the two equivalent DVs will never explain a significant amount of additional variation, and therefore will never be selected.

The bug fix was to handle the NA p-value that results from comparing the two models.
________________________________
